language: php
dist: trusty
env:
  - WP_VERSION=latest
addons:
  ssh_known_hosts: testing.optimole.com
cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"
jobs:
  include:
    - stage: test
      php: 7.0
      name: Different linters
      script:
        - composer install
        - composer run-script lint
    - php: 7.0
      name: E2E tests
      before_install:
        - openssl aes-256-cbc -K $encrypted_75c2263357b3_key -iv $encrypted_75c2263357b3_iv -in key.enc -out /tmp/key -d
      script:
        - ./bin/run-e2e-tests.sh
    - php: 5.2
      env:
        - WP_VERSION=5.1.1
      name: "Unit tests for PHP 5.2"
      dist: precise
      script:
        - ./bin/run-unit-tests.sh
    - php: 5.3
      env:
        - WP_VERSION=5.1.1
      name: Unit tests for PHP 5.3
      dist: precise
      script:
        - "./bin/run-unit-tests.sh"
    - php: 5.4
      env:
        - WP_VERSION=5.1.1
      name: Unit tests for PHP 5.4
      script:
        - "./bin/run-unit-tests.sh"
    - php: 5.5
      env:
        - WP_VERSION=5.1.1
      name: Unit tests for PHP 5.5
      script:
        - "./bin/run-unit-tests.sh"
    - php: 5.6
      name: Unit tests for PHP 5.6
      script:
        - "./bin/run-unit-tests.sh"
    - php: 7.0
      name: Unit tests for PHP 7.0
      script:
        - "./bin/run-unit-tests.sh"
    - php: 7.1
      name: Unit tests for PHP 7.1 + Code Climate coverage report
      env:
        - CC_TEST_REPORTER_ID=b6145e78ee9b35206e3eec359227b1645923db67fe0459b437cfe1589b5ab2b8
        - GIT_COMMITTED_AT=$(git log -1 --skip 1 --pretty=format:%ct)
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script:
        - "./bin/run-unit-tests.sh"
      after_script:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    - stage: deploy
      php: 7.0
      before_install:
        - nvm install && nvm use
        - npm install npm -g
      script:
        - travis_retry npm install
        - travis_retry composer install --no-dev
        - npm run build || exit 1
        - npm run release || exit 1
stages:
  - name: deploy
    if: branch = master and type != "pull_request" and repo = "Codeinwp/optimole-wp"
  - name: test
    if: type = "pull_request"
