version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7025:8080
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ~/optmlwp/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - mysql
    image: hardeepasrani/pirate-brewery:latest
    ports:
      - 8888:80
    volumes:
      - "~/wpcore:/var/www/html/"
      - "./:/var/www/html/wp-content/plugins/optimole-wp"
      - "../optimole-troubleshoot/optimole-troubleshoot.php:/var/www/html/wp-content/mu-plugins/optimole-troubleshoot.php"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_ROOT_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1

