name: E2E Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  e2e:
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to QA
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
        run: ./bin/run-e2e-tests.sh
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: E2E tests chrome
        uses: cypress-io/github-action@v2
        with:
          env: host=testing.optimole.com
          config-file: cypress.config.json
          browser: chrome
          record: true
  e2eFirefox:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: cypress-io/github-action@v2
        with:
          env: host=testing.optimole.com
          config-file: cypress.config.json
          browser: firefox
          record: true
