name: E2E Tests

on:
  pull_request:

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  e2e:
    if: "github.event.fork == false"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to QA
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
        run: ./bin/run-e2e-tests.sh
      - name: E2E tests chrome
        uses: cypress-io/github-action@v2
        with:
          env: host=testing.optimole.com
          browser: chrome
          record: true
  e2eFirefox:
    needs: e2e
    runs-on: ubuntu-latest
    container:
      image: vertigostudio/cypress-ff72
      options: --user 1001 --shm-size=2g
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          env: host=testing.optimole.com
          browser: firefox
          record: true
  empty-job:
    # if no jobs run, github action considers it a test failure -- which seems like a bug
    # this makes it so the top-level if statement for the job does not give status failure.
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Meep
        run: |
          echo "Nothing to do. This is a fork."
