name: E2E Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: ( github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name ) && ( github.actor != 'dependabot[bot]' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          composer install --no-dev --prefer-dist --no-progress --no-suggest
          npx playwright install --with-deps
      - name: Make build
        run: |
          npm run build
      - name: Make dist
        run: |
          npm run dist
      - name: Deploy to QA
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
        run: ./bin/run-e2e-tests.sh
      - name: Run E2E tests
        run: npm run e2e:run
      # Add test report artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30