name: Test PHP


on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  phplint:
    name: PHPCS on PHP 8.0
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPCS
        run: composer phpcs
  phpunit:
      name: Phpunit
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - 3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      steps:
        - name: Setup PHP version
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            extensions: simplexml, mysql
            tools: phpunit-polyfills
        - name: Checkout source code
          uses: actions/checkout@v4
        - name: Install WordPress Test Suite
          run: |
            bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
        - name: Get Composer Cache Directory
          id: composer-cache
          run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"
        - name: Setup Composer cache
          uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-
        - name: Install composer
          run: composer install --prefer-dist --no-progress --no-suggest --no-dev
        - name: Run phpunit
          run: phpunit
  phpstan:
    name: PHPStan on PHP 8.0
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: simplexml, mysql
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHPStan Static Analysis
        run: composer phpstan