name: JavaScript Tests

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches-ignore:
      - 'update_dependencies'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: ESLint & Jest Tests
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run ESLint
        run: |
          npm run lint

      - name: Run unit tests
        run: |
          npm test

      - name: Run tests with coverage
        run: |
          npm run test:coverage

